### ISSUE TITLE
Launcher just won't launch the Blender versions

### ISSUE THREAD

**Issue by MMDPrh** [Victor-IX/Blender-Launcher-V2#100]
Non of the versions of the Launcher that are above 1.16.1 works for me, it doesn't run the Blender versions at all, no matter what i do, i turned off anti virus deleted and installed everything again turned off any possible option but it wont run the version, i was hoping this new one fixes it but still nothing happens, i feel like the fix should be simple but i cant figure out what to do, i have to use 1.16.1 and in this old version stable versions are not available to download, please is there any way to fix this?

![Screenshot 2024-04-14 145228](https://github.com/Victor-IX/Blender-Launcher-V2/assets/88852150/1d96a13f-4ceb-4966-90bb-ae4c296b9189)

here after clicking on launch it just shows a number next to version and then it disappears for good, i spammed it but it just increases the number then again it disappears after a few seconds

**Comment by Victor-IX** [comment]
Can you send the log file after running the app in debug mode and trying to launch a blender build? 
To launch the BL in debug, open a terminal and use these commands (don't forget to completely close BL if it's running):
 - `cd "Path/To/BlenderLauncher/"`
 - `./"Blender Launcher.exe" -debug`


The log file is in --> `%localappdata%/Blender Launcher/`

**Comment by MMDPrh** [comment]
hello, i launched the BL in debug mode as you said and tried to open the same version 2 times, here's the log file:

[Blender Launcher.log](https://github.com/Victor-IX/Blender-Launcher-V2/files/15045772/Blender.Launcher.log)

**Comment by zeptofine** [comment]
One flaw in our logging situation is we can't really identify issues caused in the Popen process once it's not associated with blender launcher. Maybe check the [crash logs](https://docs.blender.org/manual/en/dev/troubleshooting/crash.html)

Maybe try launching the blender versions from the file explorer instead of the launcher?

**Comment by Victor-IX** [comment]
You can also try to run this version through command line with this command and see what append
`start "F:/Blender Builds Foundation/stable/blender-3.6.8+lts.f6ae60f3eeda/blender-launcher.exe"`

**Comment by MMDPrh** [comment]
> One flaw in our logging situation is we can't really identify issues caused in the Popen process once it's not associated with blender launcher. Maybe check the [crash logs](https://docs.blender.org/manual/en/dev/troubleshooting/crash.html)
> 
> Try launching the blender versions from the file explorer instead of the launcher?


The thing is every blender version does the same when i update the BL above 1.16.1, i even tried to download Blender 4.1 from the new version of the BL and launched it but still it just does nothing and the same thing will happen, launching blender from explorer is completely fine, and i use BL 1.16.1 to launch versions and it works without any problem, but as soon as i update the BL the issue appears..

**Comment by MMDPrh** [comment]
> You can also try to run this version through command line with this command and see what append `start "F:/Blender Builds Foundation/stable/blender-3.6.8+lts.f6ae60f3eeda/blender-launcher.exe"`



Here i tested the command using cmd and this is what happened, as admin and without as admin
also i showed that the previous version works fine and how the new one behaves for me :


https://github.com/Victor-IX/Blender-Launcher-V2/assets/88852150/13cf1492-f057-4243-bb02-d81b365c648f

**Comment by Victor-IX** [comment]
Okay, what you can try is to delete the `Blender Launcher.ini` file in `%localappdata%/Blender Launcher` (you can make a backup of this file if you want to save your settings) and also delete the Blender version you have installed. After that, you can launch Blender Launcher (new version), set back the path of your Blender library, and re-download the Blender version you want. Hopefully, this will fix your issue.

**Comment by MMDPrh** [comment]
I deleted every single file from Blender or the Blender Launcher using the app "everything" an did a clean installation, this time i attempted to download latest version in launcher but again after downloading and extracting, it did not launch, however something else i did test here, i launched the file that the BL tries to launch manually and it worked, after that i used "Terminal" instead of "CMD" and i executed the command you gave me before and changed the Path for this version and it worked, so it launches the Blender fine but i feel like there is something in BL's starting args im not really sure but here you can see:


https://github.com/Victor-IX/Blender-Launcher-V2/assets/88852150/10deba2b-f62e-4336-a71a-a236e3856778

is there any other thing to test?

**Comment by Victor-IX** [comment]
By default, Blender Launcher is supposed to launch the blender.exe and not the blender-launcher.exe, but I don't think the issue comes from that. 
Can you send me your .ini file and the .blinfo (in the blender version)? I will try to recreate the same installation setup on my side to check if I can reproduce that. 
Also, you can try to close all the programs running in the background and test again. Maybe one of the programs that run on your computer blocks Blender from launching from the BL.

**Comment by MMDPrh** [comment]
hello again, sure here's the BL's ini file, currently i downloaded the blender versions 3.6.11 and 4.1.1 so i'll send you the both .blinfo files for these versions here:
[files.zip](https://github.com/Victor-IX/Blender-Launcher-V2/files/15052839/files.zip)

now for the background apps i tried to close everything and on top of that just tried to turn off the antivirus or even firewall to see what would happen, but still didn't fix it for me, i dont really have any background app that interferes with processes like this one 

also only for letting you know i also launched the blender.exe itself with those same methods and it launched without any issues

**Comment by Victor-IX** [comment]
I'm not able to repro the issue on my side...
Did you try to run Blender Launcher as administrator?

**Comment by Victor-IX** [comment]
Also, can you try this build?
https://drive.google.com/file/d/1PgUiyirpfc7ZEP4kkAtFRL8rtwqCRdFR/view?usp=sharing

**Comment by MMDPrh** [comment]
Yes i tried the BL as administrator, also downloaded the build you gave and tried it as admin too, but still it did not work, but, there's something i found, im not sure if it would be related or not but i'll let you know, i looked around into BL's settings on both version an found something in BL 1.16.1 that kinda creates the similar issue, here watch this clip :


https://github.com/Victor-IX/Blender-Launcher-V2/assets/88852150/5419e573-c98c-4835-9d05-d4089cd310ed

there's an option called "Enable High DPI Scaling" and as you can see, in BL 1.16.1 when its activated by default, the BL works fine, but after i turned off this option and restarted the BL, the same issue appeared here in the older version, now i tried to do the same with the new version and also the new build you sent, but turning it off or neither back on didn't affect anything, in general i don't know what this option is for and since its an Appearance option i wasn't sure that would affect anything.
lastly there is also a tiny little detail that i thought maybe would be helpful to inform you of, on the old version after i hit restart like in the video, the BL restarts itself, but the new version wont do that, maybe something fails i dont know, but here's what i found hope this helps, also thank you for putting your time on it, if it didn't solved or anything its okay dont want to bother more than this.

**Comment by Victor-IX** [comment]
https://drive.google.com/file/d/1PnBczq98OwRAq6Lkh14QSHAclb0N-lGa/view?usp=sharing
You can try this build, I will try to find when the issue was implemented in the code base, a lot of changes happened between 1.16.1 and 2.0.24

**Comment by MMDPrh** [comment]
its so strange but this build you gave is the same as new versions and wont launch, but its okay for now i will use the new build for downloading and installing purposes and use the 1.16.1 build for launching the versions until the next updates, thank you again
