### ISSUE TITLE
Last Check time is 2 hours behind actual time

### ISSUE THREAD

**Issue by MarkBTomlinson** [Victor-IX/Blender-Launcher-V2#104]
**Describe the bug**
The check time is not the system time it is 2 hours behind.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click check and see the last checked time

**Expected behaviour**
To see the actual time.

**Comment by zeptofine** [comment]
This is due to it using the UTC time when it should be using your local timezone. this has been fixed here: https://github.com/Victor-IX/Blender-Launcher-V2/commit/522706a48d10d782000457c7f2f57ff83901a405 and should be available in main / next release
