### ISSUE TITLE
Allow separate symlink creation for each major version

### ISSUE THREAD

**Issue by Darkblader24** [Victor-IX/Blender-Launcher-V2#109]
Currently we can only create one symlink at a time. But I am working with many different Blender versions at the same time, so I would love to have an symlink for each major Blender version, so that I can continuosly install the latest minor versions without having to update all my shortcuts.

So for example instead of only having `bl_symlink`, allow the creation of e.g. `bl_3.6_symlink`, `bl_4.1_symlink` and `bl_latest_symlink`. Also it would be great if they get automatically updated if you install a new minor version or the latest version respectively.

**Comment by zeptofine** [comment]
This can be solved with the new commandline launching system in the 2.3.0 prereleases, see [Documentation: file-association#launching-via-the-commandline](https://victor-ix.github.io/Blender-Launcher-V2/file_association/?h=launch#launching-via-the-commandline)
You can create a 3.6 script by writing `./Blender\ Launcher launch -v 3.6.*`
and similar with other versions.

And a latest can be made with `launch -v "^.^.^@^"
> the `^` represents the largest / newest number 
> the `@^` represents the newest version in the query
