### ISSUE TITLE
Cannot download any build

### ISSUE THREAD

**Issue by enfeitador** [Victor-IX/Blender-Launcher-V2#110]
Whenever I try to install a blender build this download stuck in some random percentage and this error appears.
![Captura de tela 2024-05-10 102555](https://github.com/Victor-IX/Blender-Launcher-V2/assets/5193198/192a96d5-afa8-42b2-bd83-3de86397850a)

**Comment by enfeitador** [comment]
@Victor-IX can you take a look please?

**Comment by Victor-IX** [comment]
Can you run Blender Launcher in debug, repro the error and send the log file? 
`.\"Blender Launcher.exe" -debug`

**Comment by enfeitador** [comment]
@Victor-IX here is the log
[Blender Launcher.log](https://github.com/Victor-IX/Blender-Launcher-V2/files/15336679/Blender.Launcher.log)

**Comment by Victor-IX** [comment]
what version of the blender Launcher are you using ?

**Comment by enfeitador** [comment]
@Victor-IX 2.1.24

**Comment by Victor-IX** [comment]
Can you try to download the latest pre-release build? (Enable pre-release in the settings)
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/56182681/b2e1c721-d406-4cdd-ac4d-94137e94a9a2)

**Comment by enfeitador** [comment]
@Victor-IX tested, problem persists, here is the new log
[Blender Launcher1200.log](https://github.com/Victor-IX/Blender-Launcher-V2/files/15337140/Blender.Launcher1200.log)

**Comment by Victor-IX** [comment]
You can you try to delete the `.json` and the `.ini` file in the `%localappdata%/Blender Launcher/`
Complitly close Blender Launcher before removing those file by right clicking on the tray icon located on the bottom right of your main screen.
Also, try to download a daily build to see if those are working

**Comment by enfeitador** [comment]
Deleted the files and tried again, same problem, even with Daily builds @Victor-IX

**Comment by Victor-IX** [comment]
Are you able to manually download this version of Blender: https://download.blender.org/release/Blender4.1/blender-4.1.0-windows-x64.zip

**Comment by enfeitador** [comment]
Yes, I'm able to manually download that version of Blender @Victor-IX

**Comment by Victor-IX** [comment]
After some testing, I'm able to reproduce the bug by having a connection drop. 
I think the issue you have comes more from your internet connection, which might not be very stable. If it's not already the case, try to use an internet cable over Wi-Fi. 
We currently have nothing to resume the download in case of a connection drop. Maybe that is something we can try to implement if it's not too hard to do.
What do you think about that @zeptofine

**Comment by zeptofine** [comment]
Maybe. I'm not too experienced in web requests in general but as far as I can tell the urllib3 library would require us to redownload the already downloaded data to get where we were in the download so nothing is gained. unless there's some magic request metadata we can give to tell it to start midway through

**Comment by enfeitador** [comment]
> After some testing, I'm able to reproduce the bug by having a connection drop. I think the issue you have comes more from your internet connection, which might not be very stable. If it's not already the case, try to use an internet cable over Wi-Fi. We currently have nothing to resume the download in case of a connection drop. Maybe that is something we can try to implement if it's not too hard to do. What do you think about that @zeptofine

Hmmm that's weird because I have never ever had this issue before with Blender Launcher V1. I always use cable

**Comment by zxcv78092000** [comment]
I'm same like your situation I can't download any version.

**Comment by enfeitador** [comment]
Update here, today I was ablet o download a build with Blender Launcher, I did not differently, just to let you know @Victor-IX 
<img width="675" alt="Captura de tela 2024-05-27 141941" src="https://github.com/Victor-IX/Blender-Launcher-V2/assets/5193198/9147ecdf-587c-4aab-bde7-cc5e28600bbd">

**Comment by Victor-IX** [comment]
that's good news!
