### ISSUE TITLE
Feature Request: invert the columns order by clicking on their label

### ISSUE THREAD

**Issue by xan2622** [Victor-IX/Blender-Launcher-V2#119]
This is a repost of a Feature Request that I posted on the previous [Blender Launcher Github project](https://web.archive.org/web/20220321045750/https://github.com/DotBow/Blender-Launcher/issues/121) page.

---

🟡 **Is your feature request related to a problem? Please describe.**

Usually (in Explorer, Excel...), when the user clicks on the label of a column, it inverts the order of that column.
In Blender Launcher, clicking on these column labels (Version, Branch, Upload Time), the columns order is currently not inverted.

Current behaviour (clicking on column labels doesn't invert the order of the colum): 
![144669614-43549578-f25f-46d8-a896-f18aadb0bea4](https://github.com/Victor-IX/Blender-Launcher-V2/assets/1732773/7ba3218b-d164-4cd2-af80-c56583a28bda)

🟡 **Describe the solution you'd like**

Invert the columns order by clicking on their labels (Version, Branch, Upload Time).

**Comment by Victor-IX** [comment]
#120
