### ISSUE TITLE
1.16.0 - UNZIP fails

### ISSUE THREAD

**Issue by virtualrepublic** [Victor-IX/Blender-Launcher-V2#12]
**Describe the bug**
Blender Launcher can't unzip the downloaded archive.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Win 11
 - 1.16.0
 - Log file: [to attach a file to an issue, drag and drop it into the comment box]

**Additional context**

![231129_BL_1160](https://github.com/Victor-IX/Blender-Launcher-V2/assets/6465446/5ffecb9f-c53d-4388-8613-f1ab7cd72900)

**Comment by Victor-IX** [comment]
Fix in v1.16.1
