### ISSUE TITLE
Feature Request : Notify the user when trying to open the launcher while the system partition is full

### ISSUE THREAD

**Issue by etherealxx** [Victor-IX/Blender-Launcher-V2#122]
**Is your feature request related to a problem? Please describe.**
User doesn't know a certain error message that triggered when the system partition is full

**Describe the solution you'd like**
Check the free space of system partition before launching the app, then notify the user to clean the storage first before opening the app again

**Additional context**
I got this when trying to open blender partition without knowing that my system partition is full (0 bytes free)
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/64251396/c1e1f1c3-5bd4-44d8-8e51-b37bbbbffe80)

**Comment by zeptofine** [comment]
Sadly, due to how pyinstaller works, I don't think we can accommodate this and warn the user about space errors before pyinstaller extracts. This feels like a strange edge-case that would probably affect *Blender*'s proper functionality anyways
