### ISSUE TITLE
Downloads ARM64 instead of AMD64

### ISSUE THREAD

**Issue by ROBBENB** [Victor-IX/Blender-Launcher-V2#123]
Downloads ARM64 instead of AMD64 of the Blender 4.3.0 Alpha Daily Builds

**To Reproduce**
1. Go to Downloads under Daily 
2. Click on the latest 4.3.0 Alpha Blender Build
3. After download and extract 
4. Windows shows error because its for the wrong system architecture

**Expected behavior**
downloads AMD64 instead

**System (please complete the following information):**
 - Operation system: Windows 11
 - Blender Launcher version: 2.1.24

**Comment by Victor-IX** [comment]
This has been fixed in the pre-release version. You can use the pre-release version by enabling it in the General preferences and updating the Blender Launcher (bottom right of the main window).
