### ISSUE TITLE
Blender UI issues - maybe related to Blender Launcher and new changes in 4.2?

### ISSUE THREAD

**Issue by eisenbruch** [Victor-IX/Blender-Launcher-V2#125]
Fired up blender for the first time in a bit today and my UI looks like the image below.
I have tried 4.1, 4.1.1, 4.2, all through Blender Launcher. Have also restarted ye ole computer. 

Any chance this could be related to Blender Launcher in some way?

Thanks

![image](https://github.com/user-attachments/assets/d352d635-84df-46d5-abe1-ff5a3e35b493)

**Comment by Victor-IX** [comment]
Can you try to download Blender directly from the website to see if you have the same result? 
https://www.blender.org/download/

**Comment by eisenbruch** [comment]
when i install from there with normal installation path (program files) and launch that install of blender 4.2, the UI issue persists :(

any ideas what my issue might be if not BL?

**Comment by Victor-IX** [comment]
what pc and OS are you using?

**Comment by eisenbruch** [comment]
![image](https://github.com/user-attachments/assets/d54079b9-fbd4-4eab-9af4-94e320e63672)

**Comment by Victor-IX** [comment]
The first thing you can try is to update all your drivers. And do all the available updates on Windows.

**Comment by Victor-IX** [comment]
You can also try to rename the `4.2` folder to `4.2_backup` in `%appdata%\Blender Foundation\blender` this will boot Blender with new factory settings

**Comment by eisenbruch** [comment]
just finished updating all drivers, didnt fix it.

renaming the 4.2 folder (or in my case symlink) so it launched with new factory settings did work,.

now i need to figure out what in my config is messing it up. dam

**Comment by eisenbruch** [comment]
welp im an idiot. didnt even try resetting the theme. that fixed it lol. lost some custom theming but whatever.
thanks again for your help

**Comment by Victor-IX** [comment]
Ahah, nice to hear. I didn't know it was possible to break Blender like that with a theme 😅.
