### ISSUE TITLE
File is not a zip file

### ISSUE THREAD

**Issue by Sherane0** [Victor-IX/Blender-Launcher-V2#130]
**Describe the bug**
Every attempt at downloading a blender buld is greeted with this error 
![image](https://github.com/user-attachments/assets/b24ee0d4-9fce-4604-91b8-6e813dc1a640)
The issue persists on both 2.2 and 2.1.24
A week ago it was working properly
Launching the Blender Launcher on systems startup did not help
![image](https://github.com/user-attachments/assets/c080e811-531f-4af3-b35b-a9e99b73dcec)

**System:**
 - Operation system: [Windows 10]
 - Blender Launcher version: [2.2 / 2.1.24]
 - Log file: [Blender Launcher.log](https://github.com/user-attachments/files/16604231/Blender.Launcher.log)

**Additional context**
My friend on the other side of the world experiences the same issue. He has both different hardware and internet connection

**Comment by Victor-IX** [comment]
Stable builds are currently not downloadable through the Blender Launcher; the Blender Foundation is blocking the web requests... I'm currently discussing with them to solve the issue.

In the meantime, you can download blender versions [here](https://download.blender.org/release). Download the `.zip` version and place it in your stable library folder; it will be recognized by the Blender Launcher like the other builds.

**Comment by ManolloB** [comment]
Thank you Victor-IX.
I hope you find a solution with the Blender foundation, this addon is so useful in my everyday work.

**Comment by Victor-IX** [comment]
I'm still waiting for a response from them...
In the meantime, we've implemented new optimization so when this is resolved I don't think we will have this issue again 🤞

**Comment by Victor-IX** [comment]
The issue has been resolved!
