### ISSUE TITLE
libpython3.9.so.1.0: No such file or directory

### ISSUE THREAD

**Issue by RustyNova016** [Victor-IX/Blender-Launcher-V2#15]
**Describe the bug**
I cannot start blender on linux. Running it in the terminal give this error:
`[11800] Error loading Python lib '/tmp/_MEIQhgsTD/libpython3.9.so.1.0': dlopen: libcrypt.so.2: cannot open shared object file: No such file or directory`

**System (please complete the following information):**
 - Operation system: Linux Mint 21.2
 - Blender Launcher version:1.16

**Additional context**
I tried searching online for a fix, and it seems that this file is missing from the binary.

**Comment by zeptofine** [comment]
I think you're missing the package `libxcrypt`, but I've only seen this kinda issue on archlinux 🤔

**Comment by RustyNova016** [comment]
I tried installing it too but couldn't find it. Might need to find an alternate name for it

I have no idea the extent of the changes between this version and the old repo, but the old version is working perfectly.

I'll search for it when I'm back home and I'll post the answer here. If it's really a missing dependancy, it would be great to put it in the installation doc when it goes back up

**Comment by zeptofine** [comment]
So far, all we have *really* changed is the scraper, so it's definitely in my building process

**Comment by zeptofine** [comment]
@RustyNova016 Could you check the other releases and see if they occur in all of them?

**Comment by RustyNova016** [comment]
There's only one other linux release and it's 1.16.1. It still doesn't work.
Would love to help do a pull request, but I need to figure out why there's dependancy issues

**Comment by peter1960** [comment]
I see the same error on Ubuntu 22.04.3

**Comment by zeptofine** [comment]
I'll message DotBow to see how their build process is like

**Comment by llleeexxxoooppp** [comment]
Same here, Ubuntu 22.04 | BLV2 1.16.1
//
[38504] Error loading Python lib '/tmp/_MEIBAIA3W/libpython3.9.so.1.0': dlopen: libcrypt.so.2: cannot open shared object file: No such file or directory
//
BL 1.15.1 was work as should

**Comment by zeptofine** [comment]
Or find a build system that is distribution agnostic, because that is apparently something I had to be concerned about

**Comment by baldyman01** [comment]
Same with Mint 21.2 -
[39536] Error loading Python lib '/tmp/_MEIMNZCJx/libpython3.9.so.1.0': dlopen: libcrypt.so.2: cannot open shared object file: No such file or directory

**Comment by RustyNova016** [comment]
For anyone needing Ubuntu builds, you can find them here for now:
https://github.com/RustyNova016/Blender-Launcher-V2/releases/tag/v1.16.1

**Comment by freerror** [comment]
Building on a docker of Ubuntu is a way to do it from your Arch system without static linking things.

It could use some tweaks (pdm set up, python version), but ChatGPT 4 suggestion on how to do this:

To fully automate the process of cloning a repository, running a build script, and retrieving the output files within an Ubuntu Docker container, all from an Arch Linux environment, you need to:

1. Write a Dockerfile for an Ubuntu-based container.
2. Write a script on your Arch Linux machine to:
   - Build and run the Docker container.
   - Execute the necessary commands inside the container.
   - Retrieve the output files back to the Arch host.

Here's a step-by-step guide:

### Step 1: Create a Dockerfile

Create a `Dockerfile` that sets up an Ubuntu environment with all the necessary dependencies for your project. For example:

```Dockerfile
# Use Ubuntu as the base image
FROM ubuntu:latest

# Install Git and any other dependencies
RUN apt-get update && \
    apt-get install -y git python3 python3-pip

# Set a working directory (change as per your project's need)
WORKDIR /usr/src/app

# Copy build script into the container (assuming you have a build script)
COPY build_script.sh /usr/src/app/

# Give execution permission to the build script
RUN chmod +x /usr/src/app/build_script.sh
```

### Step 2: Write a Build and Execution Script on Arch

Write a shell script on your Arch Linux system to automate the process:

```bash
#!/bin/bash

# Name of your Docker image
IMAGE_NAME="my_build_env"

# Clone the repository (assuming you have the URL)
git clone [REPO_URL] project_folder

# Build the Docker image
docker build -t $IMAGE_NAME .

# Run the container, execute the build script, and copy out the results
docker run --name temp_container -v $(pwd)/project_folder:/usr/src/app $IMAGE_NAME /usr/src/app/build_script.sh

# Copy the output files from the container to your host
docker cp temp_container:/usr/src/app/output_folder ./output_folder

# Clean up: remove the container
docker rm temp_container
```

Replace `[REPO_URL]` with the URL of your Git repository. The script does the following:

- Clones the Git repository.
- Builds a Docker image based on the `Dockerfile`.
- Runs the container and executes the build script inside it.
- Copies the output files from the container to the host.
- Removes the container after the job is done.

### Step 3: Run Your Automation Script

Make your script executable and run it:

```bash
chmod +x my_automation_script.sh
./my_automation_script.sh
```

### Notes:

- Make sure Docker is installed on your Arch Linux system.
- Adjust the paths and script names according to your project structure and requirements.
- If your build process requires additional environment variables or configurations, modify the Dockerfile and the script accordingly.
- If the output files are in a different path inside the container, adjust the `docker cp` command to the correct path.

This setup ensures that your build process is completely automated, running inside an Ubuntu container, and all managed from your Arch Linux system.
