### ISSUE TITLE
Traceback error

### ISSUE THREAD

**Issue by cloudberryowo** [Victor-IX/Blender-Launcher-V2#152]
i am not good at explaining but i have a windows 10 computer and when i try to launch it this happens
![2024-10-23 (7)](https://github.com/user-attachments/assets/7f30f3e4-5bae-4dee-9a85-8277f1c1033f)
its some kind of socks4 error idk why its happening

**Comment by zeptofine** [comment]
Solved in discord last night

Basically, the old default port number is higher than what ports can actually support. To fix this, open up the ini settings file and delete your proxy settings
Then if you intended to use the proxy, fully set it up with a correct port number before restarting the application.
