### ISSUE TITLE
Will there be a MacOS version at some point?

### ISSUE THREAD

**Issue by ghc198** [Victor-IX/Blender-Launcher-V2#153]
Just asking.

**Comment by illusional** [comment]
FWIW, I built this today on Mac, the main thing I had to do was upgrade `pyqt5-qt5` (for which there was a comment suggesting I'd have to do this).
What's the reason for bundling the `stable_builds_api.json` in the build-mac.sh: https://github.com/Victor-IX/Blender-Launcher-V2/blob/cff0933039b3305dd78e9e627ec650a88318dca1/scripts/build_mac.sh#L17

Is there anything I can do to help out with the testing - I didn't have any other issues, I was able to download the latest version of blender and launch it. Seems like it should be possible to do with a Github action?

**Comment by Victor-IX** [comment]
You can remove the `stable_build_api.json` for now. This is to reduce the number of requests to the Blender server on the first launch, but it's not mandatory.

It would likely be possible to build a version with GitHub Actions, but as I mentioned, we don't have access to a Mac. So, if a bug occurs on the Mac version, it would be difficult for us to debug and fix it. This is the main reason it's not officially supported. If you or someone else is willing to help with testing and fixing bugs for the Mac version, we could consider officially supporting it.

**Comment by illusional** [comment]
Yeah, happy to help out with debugging from time to time. Over the next couple of days I'll fork the repo, and try to get a build-mac action working so it can be attached to future releases.

Could we expand the `pyqt5-qt5` range to include one that builds on Mac?

I couldn't attach it here as the .zip is > 25MB, so I've created a release on my fork: https://github.com/illusional/Blender-Launcher-V2/releases/tag/mac-2.3.0-prerelease

Heads-up, this does NOT work on an intel mac.

**Comment by xx88xx** [comment]
@illusional any work on a mac port of this, even if it's just ARM (m1 etc) macs is MUCH APPRECAITED. Thank you so much!! 

Just tested it and it seems to work great so far!

**Comment by xx88xx** [comment]
@illusional one thing I noticed, it's listing both LTS, x64 and ARM in the list. Is there are a way determine what an LTS release is? I'm assuming it's either x64 or Arm right? Or are LTS somehow both?

![image](https://github.com/user-attachments/assets/b65abe1d-afaf-4d22-9329-03b90c944e6d)

**Comment by zeptofine** [comment]
Pinning since this is a hot topic and probably will be for a while

**Comment by Victor-IX** [comment]
> @illusional one thing I noticed, it's listing both LTS, x64 and ARM in the list. Is there are a way determine what an LTS release is? I'm assuming it's either x64 or Arm right? Or are LTS somehow both?

For Windows we filter builds to only show the compatible build, I'm sure we could have something similar for Mac to remove confusion 
This has been implemented in https://github.com/Victor-IX/Blender-Launcher-V2/pull/106

**Comment by Victor-IX** [comment]
> Could we expand the `pyqt5-qt5` range to include one that builds on Mac?

It seems that there is no PyQt5 version compatible with all three OS at the same time. What we will do in the future is move the project to PySide6 instead of PyQt5. I created this task for it: https://github.com/Victor-IX/Blender-Launcher-V2/issues/160

**Comment by illusional** [comment]
Hey @Victor-IX, looks like the MacOS build was attached to the latest release, should we close this issue, and people can reopen if there are issues?

**Comment by Theunderscor3** [comment]
Hi! could someone please help out with a Mac OS x86_64 build?
