### ISSUE TITLE
1.6 & 1.6.1 doesn't open at all under Linux KDE

### ISSUE THREAD

**Issue by genesis2303** [Victor-IX/Blender-Launcher-V2#17]
**Describe the bug**
It simply doesn't open at all, no try icon, no welcome screen to choose folder nothing, I can hit enter till I break my keyboard.
Checked version of this thing from documentation: ldd (Debian GLIBC 2.36-9+deb12u3) 2.36
so it should be working, but it's not. 1.5 opens, but obviously it doesn't download new versions.

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Operation system: [e.g. Windows 10]
 - Blender Launcher version: [e.g. v1.0.0-rc.1]
 - Log file: [to attach a file to an issue, drag and drop it into the comment box]

**Additional context**

**Comment by zeptofine** [comment]
This should be resolved in the next update
