### ISSUE TITLE
Blender launcher download ARM build for 4.3

### ISSUE THREAD

**Issue by AntoninHS** [Victor-IX/Blender-Launcher-V2#171]
The launcher is downloading the ARM build for blender 4.3, instead of the x86, so I cant use it on my computer

**Comment by drollicdotcom** [comment]
Ditto.   Wasn't there already a fix made for this?

**Comment by Victor-IX** [comment]
The issue has been fixed, and a new version is now available! You can update your Blender Launcher to version 2.3.0
The update button will be available in the bottom-right corner of the launcher window. If you don't see it, click on the Check button in the bottom-left corner, and after a few seconds, the option will appear.

> Ditto. Wasn't there already a fix made for this?
@drollicdotcom There was one for the daily build, not the stable build. This is the first time the Blender Foundation has released a stable ARM build.

**Comment by B1Trash** [comment]
Fantastic, thanks Victor!
