### ISSUE TITLE
unable to extract the current release

### ISSUE THREAD

**Issue by Zap-42** [Victor-IX/Blender-Launcher-V2#172]
hi, I am getting an error on extracting the current build.  Two release candidates yesterday but one caused this error. The LTS from today shows  an error when extracting. It says it is the Wrong machine type:

![Screenshot 2024-11-19 091424](https://github.com/user-attachments/assets/815f3cef-5fd4-4756-8bd0-2bbf3e3ab1d2)

**Comment by anurag-ekka** [comment]
I have the same issue. I even tried the 2.3 rc 2 version to download and still shows the same error.

**Comment by Blood-PawWerewolf** [comment]
> I have the same issue. I even tried the 2.3 rc 2 version to download and still shows the same error.

it's because the launcher is scraping the wrong system architecture (it's trying to install the ARM version and not the x86-64 version).

**Comment by drollicdotcom** [comment]
Ditto.

**Comment by drollicdotcom** [comment]
Looks like this is potentially fixed in the code on November 23rd:
https://github.com/DotBow/Blender-Launcher/commit/07d5c114fdfd495d01e73ea144e93ace89866350

But looks like development halted there, with no new releases.

**Comment by drollicdotcom** [comment]
I think this new version of Blender launcher is already dead:

"This repository has been archived by the owner on Nov 28, 2023. It is now read-only."

**Comment by Victor-IX** [comment]
I will look at this issue when I'm back from work. At the moment, we handle the ARM version for daily builds but not for stable ones.

@drollicdotcom This repo is not dead. The old one was abandoned ~2 years ago, and we took back the development of it on this forked version.

**Comment by Victor-IX** [comment]
The issue has been fixed, and a new version is now available! You can update your Blender Launcher to version 2.3.0
The update button will be available in the bottom-right corner of the launcher window. If you don't see it, click on the Check button in the bottom-left corner, and after a few seconds, the option will appear.
