### ISSUE TITLE
Support Debug options for Bforartists builds

### ISSUE THREAD

**Issue by xan2622** [Victor-IX/Blender-Launcher-V2#180]
**Describe the bug**
In Blender Launcher 2.3.2, if you try to launch Bforartists 4.3.0 thanks to the Debug options, it will make Bforartists crash at startup.

**Error**
> '"E:\Blender_Builds\bforartists\blender-4.3.0-window+bforartists.1afda666ee6b\\blender"'  is not recognized as an internal or external command, operable program or batch file'

**Expected behavior**
It would be convenient if Blender Launcher allowed to open Bforartists with Debug options.

**Screenshots**
![image](https://github.com/user-attachments/assets/d41de6b1-75ff-4990-98f3-1826ddfe50d3)

**System (please complete the following information):**
 - Operation system: Windows 11
 - Blender Launcher version: 2.3.2

**Comment by Victor-IX** [comment]
This bug is not caused by the Blender Launcher. When you try to open the .bat file manually to launch BforArtist with Debug Log, you experience the same behaviour. You can report this bug directly to BforArtist.

**Comment by Draise14** [comment]
Could you help me clarify what bat file you are refering to? Would be these that you use? 

![image](https://github.com/user-attachments/assets/dc1e2568-6dc9-4593-9fa1-c0e14d2cbc5d)

I'll report and get that fixed.

**Comment by Draise14** [comment]
Reported, will get fixed for 4.4
https://github.com/Bforartists/Bforartists/issues/4842
