### ISSUE TITLE
GUI closes during/before extraction takes place

### ISSUE THREAD

**Issue by zeptofine** [Victor-IX/Blender-Launcher-V2#19]
**Describe the bug**
The GUI closes nearly every time extraction starts. I have litterally no idea why this happens

**To Reproduce**
1. Open the launcher
2. Go to downloads
3. download any build
4. ???
5. it closes
6. profit

**Expected behavior**
It doesn't close lmao

**Comment by virtualrepublic** [comment]
Confirmed on Win 11. But it closes and the version has been unzipped successfully.

**Comment by L0Lock** [comment]
Also the `Blender Launcher.log` doesn't log anything when that happens. Should this be reported as its own issue as well?

**Comment by Victor-IX** [comment]
We can probably do the new release this week
