### ISSUE TITLE
Stable Builds unavailable after install

### ISSUE THREAD

**Issue by SanderEwen** [Victor-IX/Blender-Launcher-V2#20]
After "installing" Blender Launcher, It's not possible to see stable versions of Blender in the download folder (Stable Builds are currently unavailable)

1. Go to 'Stable - Downloads'

<img width="638" alt="image" src="https://github.com/Victor-IX/Blender-Launcher-V2/assets/108576375/67ae4ea7-6150-4a39-bac6-15fc1b2e8cdf">

**System**
 - Windows 11
 - Blender Launcher version: 1.16.1

**Comment by genesis2303** [comment]
It's written directly in releases with ! mark:
_Blender Foundation is currently blocking the request on the /release website for the stables versions making it impossible to retrieve those versions, this issue will be fixed during the week_
