### ISSUE TITLE
Patch reference isn't showing

### ISSUE THREAD

**Issue by IlyasseL34** [Victor-IX/Blender-Launcher-V2#23]
**Describe the bug**

The reference of the Patch isn't displayed until you download it.

**To Reproduce**
Open Blend Launcher
Go to Downloads
In the Experimental Tab

**Expected behavior**
The PR reference or the name of the patch should be displayed before download.

**Screenshots**
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/58734124/b609b5d6-94aa-425e-9d31-de33c3bc1a33)

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: 1.16.1

**Comment by juryrigging** [comment]
The relevant field on Blender builds is "variant", if that helps work out the issue.
