### ISSUE TITLE
Reload of Custom builds will cause duplication of Favorites entries

### ISSUE THREAD

**Issue by Kaitou-3D** [Victor-IX/Blender-Launcher-V2#34]
If you have a custom version of blender (I have a version of Goo-engine) set as a favorite, and you hit reload, the entry will duplicate in the 'Favorites'.
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/26198203/b7b1b6a9-3a26-4ab4-9489-585aa3369a34)

![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/26198203/5e277275-3ff7-452c-a2ff-13d2d1df6f43)

**Comment by zeptofine** [comment]
This has been resolved last week on https://github.com/Victor-IX/Blender-Launcher-V2/commit/deb6d5da3defea6e20e2b6bf11a84503d8ce77c7, it will be available next update

**Comment by zeptofine** [comment]
@Victor-IX Should issues like these that were resolved stay open until the next release or should they get closed? because it's likely people won't check the closed issues to see if it's already been resolved

**Comment by zeptofine** [comment]
we could also make a `fixed` tag.

**Comment by Victor-IX** [comment]
Yeah, I think the Fixed tag is a good idea! and keeping issues open until the next release is the best thing to do to prevent duplicates.

**Comment by Gedudo** [comment]
Hi, I wanted to bring up that this issue might have resurfaced in my current version 2.6.1. It however seems to reset back to normal once I restart the program. Sending any of the fake entries to the trash will delete their original single build that actually exists.

I guess it slightly differs from the original issue as this happens in the Custom Library, there are no issues in the favorite tab as there is no reload button present there. When I reload the library, it does not duplicate the entrys in the favorites tab.

There might however be a minor issue with the remove from favorites text

<img width="188" height="166" alt="Possible remove text issue" src="https://github.com/user-attachments/assets/36e7309d-023e-4c0e-80a1-8e046785b579" />

Here is a video showing the duplication behavior happening currently:

https://github.com/user-attachments/assets/68b4f2d0-ae51-45b0-ae97-a267b8190b87
