### ISSUE TITLE
Recognize blender builds with custom names, like BforArtists

### ISSUE THREAD

**Issue by Kaitou-3D** [Victor-IX/Blender-Launcher-V2#35]
Attempted to add [Bforartist ver 3.6.1](https://www.bforartists.de/) into my custom folder, but the launcher isn't recognizing the folder.

As an aside, I did try making a custom .blinfo for the folder, but still not appearance

![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/26198203/dab4975c-626c-495d-9423-38e937f11b24)

![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/26198203/58a531fe-04ff-4834-80b5-9714b4eb4a79)

**Comment by zeptofine** [comment]
it's likely because it doesn't use the usual blender.exe naming scheme
