### ISSUE TITLE
There is no documentation site

### ISSUE THREAD

**Issue by shiena** [Victor-IX/Blender-Launcher-V2#4]
**Is your feature request related to a problem? Please describe.**
Pressing the document button also opens a 404 page.

![image](https://github.com/Victor-IX/Blender-Launcher/assets/1295639/e65e5925-7d13-4517-bc9a-e1b99686cbc3)

**Comment by xan2622** [comment]
DotBow, the original author of *Blender Launcher* has archived its Github repository https://github.com/DotBow/Blender-Launcher (closing at the same time all Github issues and the documentation page).

The former documentation page is still accessible thanks to the *Internet Archive WayBack Machine* website: 
https://github.com/DotBow/Blender-Launcher

I suggest to create a new documentation page based on this 'backup'.

**Comment by shiena** [comment]
@xan2622 
You can also restore documents by importing the [gh-pages branch](https://github.com/DotBow/Blender-Launcher/tree/gh-pages) instead of using Waybak Machine.

**Comment by xan2622** [comment]
@shiena : Do you know if the content of (now vanished) Github Issues can be recovered the same way?

**Comment by shiena** [comment]
@xan2622 
You can restore a document site by importing the gh-pages branch and following the steps below.
https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/creating-a-github-pages-site-with-jekyll

**Comment by zeptofine** [comment]
👍 I'll try to get this up and running

**Comment by zeptofine** [comment]
I've built the branch, now its up to Vic to upload it to their site
