### ISSUE TITLE
Blender Launcher crashes during init on Gnome under Wayland

### ISSUE THREAD

**Issue by johnyc90** [Victor-IX/Blender-Launcher-V2#47]
**Describe the bug**
Blender launcher is not lauching on Fedora systems under gnoe wayland. Running it through the terminal yields the following messages:

```
Traceback (most recent call last):
  File "main.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "windows/main_window.py", line 29, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "pynput/__init__.py", line 40, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 493, in exec_module
  File "pynput/keyboard/__init__.py", line 31, in <module>
  File "pynput/_util/__init__.py", line 76, in backend
ImportError: this platform is not supported: ('failed to acquire X connection: Can\'t connect to display ":0": b\'Authorization required, but no authorization protocol specified\\n\'', DisplayConnectionError(':0', b'Authorization required, but no authorization protocol specified\n'))

Try one of the following resolutions:

 * Please make sure that you have an X server running, and that the DISPLAY environment variable is set correctly
[12069] Failed to execute script 'main' due to unhandled exception!
```

**To Reproduce**
* Using a Fedora version 37 or up, logged using Gnome Wayland.
* Open a terminal window.
* Navigate to the Blender Launcher 

**Expected behavior**
For Blender Laucher to run.

**System (please complete the following information):**
 - Operation system: Fedora 37/38/39
 - Blender Launcher version: any

**Additional context**
This problem had been reported on Dotbow's repo previously. This is sure to happen on Fedora versions newer than 36 unsing gnome and wayland, but other people have had this same problem under other OSs. This seemed to be related to how Gnome versions 43 where using GTK4 toolkit under wayland or something like this, so I think that anything running Gnome 43 and over under wayland might display the issue.

**Comment by zeptofine** [comment]
I guess pynput requires an X server (or xwayland) to be running. I'll see if that can possibly be made optional

**Comment by johnyc90** [comment]
Apparently pyinput should work under wayland. But the build_linux.sh and build_linux_debug.sh files point to hidden-imports of _xorg files:

--hidden-import "pynput.keyboard._xorg" \
--hidden-import "pynput.mouse._xorg" \
--hidden-import "python-xlib" \

Is it possible that the linux version is explicitly using the xorg versions of those dependencies instead of a platform agnostic version?

**Comment by zeptofine** [comment]
The packager needs to use these hidden imports because they aren't static, so pyinstaller cannot track them. see here: https://github.com/moses-palmer/pynput/issues/312

and during importing, pynput uses this function, where in the highlighted text, specifies which modules to use:
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/54873330/5163faad-3899-42ee-adf5-60a4253c854d)

And I think a fully platform agnostic version is impossible because it needs different methods of collecting keystrokes for different oses. `pynput.keyboard`'s version of platform agnostic is selecting the correct backend during runtime

![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/54873330/636d43a7-7579-4c08-b13f-f807a21af125)

The XLib import seems to have been added actually *for* Fedora... not sure why though

**Comment by johnyc90** [comment]
After doing some digging I built it myself at home and I got a functioning version of the launcher. I suppose it may be related to the build environment.
One thing I noticed is that while installing the dependencies through pdm, the installation of evdev (the pynput dependency that is used to solve wayland compatibility) fails to install. This was due to missing the required distro's python development package (python3.10-devel in my case since 3.10 is the python version i'm using).  After that everything went smooth.
There was a separate bug that issued, with python complaining about unexpected floats, but I'll make a separate issue for that.

**Comment by zeptofine** [comment]
strange, i thought i fixed that last thing

**Comment by johnyc90** [comment]
Oh! you fixed it on commit c2ed6488c4c38b6586d17efd2bfd38460667bff1.

**Comment by zeptofine** [comment]
ok, now I'm curious, does the global hotkeys actually work for you on Wayland with the custom build? it has *never* worked for me on Wayland. I always assumed it was because of the security stuff regarding Wayland

**Comment by Victor-IX** [comment]
Bug fix, closing this issue
