### ISSUE TITLE
Stable Versions only show a single stable release to download at a time.

### ISSUE THREAD

**Issue by OddHero** [Victor-IX/Blender-Launcher-V2#51]
**Describe the bug**
The stable version download tab shows only the first version that is higher or equal to the set minimum stable release setting.

**To Reproduce**
1. Go to Blender Builds Tab in the Settings
2. Change Version to anything. ex. 2.40
3. restart launcher
4. Go To downloads Tab
5. Only 1 Version listed

**Expected behavior**
All stable Versions starting with the minimum set version should show up in the list

**Screenshots**

https://github.com/Victor-IX/Blender-Launcher-V2/assets/1459179/4910db5d-2ea5-4ed3-9379-7848bda3e835

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: 1.16.1 (build from current main at commit: f284074a9494f066d4d938310fc5f996f48c1a8f)
 - Log file: empty!

**Additional context**
Probably related to #36

**Comment by zeptofine** [comment]
ok, I've tracked the culprit. the other night I made this code which was only supposed to fix an unknown build_hash https://github.com/Victor-IX/Blender-Launcher-V2/blob/f284074a9494f066d4d938310fc5f996f48c1a8f/source/threads/scraper.py#L153-L156

Click the upload time and it'll show the hash, likely it's a bunch of zeros. I'll see if I can roll that back

**Comment by zeptofine** [comment]
thanks for reporting this so early!
