### ISSUE TITLE
Impossible to move BL using internal moving pannels on Wayland

### ISSUE THREAD

**Issue by FuzzyExpress** [Victor-IX/Blender-Launcher-V2#52]
**Describe the bug**
Wayland's security prevents windows from moving themselves (I have not find a way around it), Blender Launcher's movement by click dragging the top, left or bottom of the of the window does nothing.

https://github.com/Victor-IX/Blender-Launcher-V2/assets/127012288/33a0e0bf-6afa-4e10-a61b-8194ac2a52bb

*Note that the last (and only functional) attempt to move the window was done with the KWin `Meta` + `Left Click Drag` function I enabled in my settings.

**To Reproduce**
Log into a Wayland Session
Open Blender Launcher
Try to move it 

**Expected behavior**

It can be seen working normally on X11, where click dragging the sides moves the window.

**System (please complete the following information):**
 - Operation system: Kubuntu 23.10 | KDE Plasma 5.27.8 | Wayland | 6.6.8-x64v3-xanmod1 Kernel.
 - Blender Launcher version: 
       Blender_Launcher_v1.16.1_Ubuntu_x64
       or
       Blender_Launcher_v1.16.1_Linux_x64 (It does not tell me)
 
 - Log file:  
[Blender Launcher.log](https://github.com/Victor-IX/Blender-Launcher-V2/files/14000056/Blender.Launcher.log)

**Additional context**
Given that this is a Wayland thing and not a bug with this tool, not much can be done.
Also the log errors don't appear to be related at all, in my experience, telling a PyQt5 window to move, provides no evidence that an error occurred. The window that was told to move also shows internally that it did move, despite not having moved.
I would recommend added a setting to enable the system Title Bar and Frame to move it, or maybe making it automatic if Wayland is detected.
Edit: Having said that though, Cider 2, Opera, Steam, Modrinth App, and FireFox's custom title bars work just fine on Wayland, no clue why that would be.

**Comment by zeptofine** [comment]
I am up for an option to use the system title bar. infact before V2 came out I removed the custom one in my fork bcus it annoyed me at the time!

**Comment by zeptofine** [comment]
also, I can replicate this :p
