### ISSUE TITLE
Windows Security detecting trojan

### ISSUE THREAD

**Issue by boristsr** [Victor-IX/Blender-Launcher-V2#59]
**Describe the bug**
The latest version 2.0.24 is being reported as containing a trojan by Windows Security.

**To Reproduce**
1. Download latest version
2. Extract
3. Wait for windows to pop up error message

**Expected behavior**

**Screenshots**
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/2999162/5d0cfe86-6a12-463c-a1db-8de56afb56e7)

**System (please complete the following information):**
 - Operation system: Windows 11
 - Blender Launcher version: 2.0.24
 - Log file: [to attach a file to an issue, drag and drop it into the comment box]

**Additional context**

**Comment by Victor-IX** [comment]
I sent the last version to be reviewed by Microsoft, the detection has been removed, if the program is still detected as malicious, you can follow the steps on the screen to obtain the last malware definition
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/56182681/6a394660-61ba-4413-bd9b-eca426b0c781)

**Comment by boristsr** [comment]
Thanks! Can confirm it's not triggering detection anymore.
