### ISSUE TITLE
Linux build NEEDED

### ISSUE THREAD

**Issue by jurassicjordan** [Victor-IX/Blender-Launcher-V2#6]
**Is your feature request related to a problem? Please describe.**
The original DotBow built has linux builds. Those of us with linux workstations and linux render farms would like a linux build being available

**Describe the solution you'd like**
Please make a linux build available in case the pull request to DotBow's repo is not accepted

**Describe alternatives you've considered**
A simple prebuilt binary that is included under the releases would be a godsent.

**Comment by Victor-IX** [comment]
Linux Version Available here
https://github.com/Victor-IX/Blender-Launcher-V2/releases/tag/v1.16.0
