### ISSUE TITLE
2.0.24 Breaks previously installed Blender Builds:

### ISSUE THREAD

**Issue by Trife66** [Victor-IX/Blender-Launcher-V2#65]
**Describe the bug**
When I launched (Blender launcher) I was greeted with a notification claiming that there was an update 2.0.24 I proceeded to update and when update was finished I was unable to open up my previously installed blender builds 4.02 stable\4.02 Kcycles Stable, Instead I was greeted with a red delete button instead of launch and a error "is Damaged" so I deleted it, then redownloaded my Builds & still got the same error.😡 I am now unable to use (blender launcher) and have resorted back to just starting up blender through short-cut on desktop. Has anybody else experienced this?  Is there a fix? please and thank you.

**To Reproduce**
1. Just Update

**Expected behavior**
After update when blender launcher 2.0.24 starts up you will receive a red delete button over previously installed blender built with a message claiming build is damaged

**Screenshots**

**System (please complete the following information):**
 - Operation system: [Windows 11]
 - Blender Launcher version: [2.0.24]
 - Log file: [ if someone could please explained to me the location of this log file that would be very helpful ! ]

**Additional context**
I thank you in advance
![Screenshot 2024-02-01 123429](https://github.com/Victor-IX/Blender-Launcher-V2/assets/1622571/b6c4f46b-fa77-487d-b342-9f2b2e59bdaf)

**Comment by zeptofine** [comment]
The log file is the text document next to the Blender Launcher executable, please send it

**Comment by Trife66** [comment]
[Blender Launcher.log](https://github.com/Victor-IX/Blender-Launcher-V2/files/14129271/Blender.Launcher.log)

**Comment by zeptofine** [comment]
https://github.com/Victor-IX/Blender-Launcher-V2/blob/2edd61f7132363ec57bd7adc9f795d99fdff7568/source/modules/build_info.py#L107
It seems that your blender version is not sending any data back. Could you run the launcher from the command line with the `-debug` flag and send the log again? I will do some testing

**Comment by Trife66** [comment]
Can you write out an example of the command that I run in command line please somehow I'm not getting it to launch with the - debug

**Comment by Trife66** [comment]
"C:\Users\IDesign66\Documents\Blender_Launcher_v2.0.24_Windows_x64\Blender Launcher.exe" -debug  
(okay I got it to launch like this)
[Blender Launcher.log](https://github.com/Victor-IX/Blender-Launcher-V2/files/14129411/Blender.Launcher.log)

**Comment by Trife66** [comment]
Please let me know if this suffices?
