### ISSUE TITLE
Blender 4.0.2 broken after every BL restart

### ISSUE THREAD

**Issue by luisseyfer** [Victor-IX/Blender-Launcher-V2#70]
**Describe the bug**
Blender version 4.0.2 is broken after every relaunch BL
Other Blender Versions seem to work correctly

`$ ./BlenderLauncher
[2024-02-11 18:33:25,198:ERROR] time data '05-Dec-23-07:41' does not match format '%d-%b-%y-%H:%M'
Traceback (most recent call last):
  File "modules/tasks.py", line 108, in run
  File "modules/build_info.py", line 248, in run
  File "modules/build_info.py", line 211, in read_build_info
  File "modules/build_info.py", line 54, in from_dict
  File "_strptime.py", line 568, in _strptime_datetime
  File "_strptime.py", line 349, in _strptime
ValueError: time data '05-Dec-23-07:41' does not match format '%d-%b-%y-%H:%M'
[2024-02-11 18:33:25,237:ERROR] time data '05-Dec-23-07:41' does not match format '%d-%b-%y-%H:%M'
`

**To Reproduce**
1. Launch BL - 'Build *Blender 4.0.2 ....* is damaged!'
2. Click on 'Delete'
3. Go to 'Downloads'
4. Reinstall  Blender 4.0.2
5. Quit BL
6. Relaunch BL - 'Build *Blender 4.0.2 ....* is damaged!'

**Expected behavior**
Keep a working  Blender 4.0.2 after installation like other versions

**Screenshots**
![Screenshot_20240211_181213](https://github.com/Victor-IX/Blender-Launcher-V2/assets/44850868/eaffa968-5a97-4db9-b93a-fc341b795481)

**System (please complete the following information):**
 - Operation system: Kubuntu 22.04
 - Blender Launcher version: 2.0.24
 - Log file: [Blender Launcher.log](https://github.com/Victor-IX/Blender-Launcher-V2/files/14233416/Blender.Launcher.log)

**Additional context**
Related to #65 and/or #55???

**Comment by zeptofine** [comment]
I hate these kinds of issues... I am LITTERALLY exporting it AS the format it wants...

![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/54873330/77579a5c-52b2-43e7-bfe8-9f4b65adbc94)

**Comment by zeptofine** [comment]
@luisseyfer What is your locale set to? I think it can't parse the time data because the definition of '%d-%b-%y-%H:%M' is different based on your locale

**Comment by luisseyfer** [comment]
`$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
`

**Comment by zeptofine** [comment]
Ah, yep, de_DE.UTF-8. that's read as 5 Dec 2023, 14:19 when in DE it's read as 5 **Dez** 2023, 14:19.
I can replicate this. 
In https://github.com/Victor-IX/Blender-Launcher-V2/commit/76688dadb09eab79d29bca8bdefcc28a0200599f I switched the BuildInfos to save using the ISO format, so hopefully this doesn't happen in the future.

For now, try using `LC_TIME=en_US.UTF-8 ./BlenderLauncher` to launch it

**Comment by luisseyfer** [comment]
Thanks, it works

**Comment by luisseyfer** [comment]
Thanks, it works
