### ISSUE TITLE
Triggering Windows Security Threat

### ISSUE THREAD

**Issue by eisenbruch** [Victor-IX/Blender-Launcher-V2#75]
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/6180294/df16111b-8900-4a40-9130-8bbe9cef0e49)

When I build from main the exe is seen as a threat in windows security

do I have anything to worry about?

**Comment by zeptofine** [comment]
This happens a lot with apps that are built with Pyinstaller. You don't have anything to worry about; see https://github.com/Victor-IX/Blender-Launcher-V2/issues/59

You are seeing the same error now because you likely built a version of the software that is unfamiliar to Windows yet (master?)

**Comment by eisenbruch** [comment]
got it. ill have to figure out how to make the exception. thanks!
