### ISSUE TITLE
Installing new User Custom Build won't have any option of "reload"

### ISSUE THREAD

**Issue by Gerstmann-Bradley** [Victor-IX/Blender-Launcher-V2#76]
**Describe the bug**
If the custom build section is empty, there will be a rebuild button.
If there's any build in the custom build section, this button will disappear.

What's really problematic is it will not automatically load new builds in that section.
and without reload button / other methods, newly added blender build won't be registered in launcher.
as a result, I only have 1 custom build in the launcher, while I have 2 builds in the destination folder.
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/55994236/073c09b6-a808-4759-b2c5-ce888dcacecf)

**Comment by zeptofine** [comment]
Have you tried the "Reload" button above the Launch button? I should really put an icon there

**Comment by Gerstmann-Bradley** [comment]
damn, you are right, didn't find it. Sorry for the misalarm.
