### ISSUE TITLE
Previously installed versions stuck flagged as "installed" after uninstalling

### ISSUE THREAD

**Issue by Syndaryl** [Victor-IX/Blender-Launcher-V2#78]
**Describe the bug**
The new feature in the Downloads tab (installed versions having the Download button disabled and changed to blue background with text "Installed") is preventing reinstallation after uninstalling.

**To Reproduce**
1. Go to Library, Daily
2. Right click on a build
3. Select Delete from Drive
4. Wait until deleted
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/8820565/0fc78acc-89a9-4085-9ce8-c6f73fc63e8e)
5. Confirm build folder deleted from daily folder
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/8820565/2a6f54f6-e541-4410-a022-e61f7263c7f5)
6. Go to Downloads, Daily
7. Observe "stuck" "installed" buttons.
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/8820565/c0e45df5-4c91-4a4d-9f18-ba4c63ea0875)

**Expected behavior**
I expect Blender Launcher to know it uninstalled the versions and allow me to download them again. 
Ideally, it would also notice the folder being missing if deleted manually.

**Screenshots**

**System (please complete the following information):**
 - Operation system: Windows 10
 - Blender Launcher version: 2.024
 - Log file: 
[Blender Launcher.log](https://github.com/Victor-IX/Blender-Launcher-V2/files/14576603/Blender.Launcher.log)
[Blender Launcher.ini.txt](https://github.com/Victor-IX/Blender-Launcher-V2/files/14576615/Blender.Launcher.ini.txt)

**Additional context**
I am in the Canadian region, with my OS set to Canadian English language.

**Comment by zeptofine** [comment]
As of 158118a934b2c5965dce8e8de975ecc89a2e0820, this was addressed, and should be available next release!
