### ISSUE TITLE
No stable builds available

### ISSUE THREAD

**Issue by andersmmg** [Victor-IX/Blender-Launcher-V2#79]
**Describe the bug**
There are never any stable builds listed, so I have to use the daily builds or experimental.

**To Reproduce**
1. Go to the 'Stable' tab in 'Downloads'
2. It says 'No new builds available'

**Expected behavior**
It should show the current stable versions.

**Screenshots**
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/16022203/620008eb-0c3e-433e-a42d-0883f6deafbc)

**System (please complete the following information):**
 - Operation system: Arch Linux
 - Blender Launcher version: 2.0.24

**Additional context**
It's always done this, I assumed it was a one time thing when I first tried the launcher but that was a few months ago.

**Comment by zeptofine** [comment]
Ah shit, It looks like they are getting botted again @Victor-IX
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/54873330/77e3ff78-abbe-4d66-8dd8-d7f07abaf18b)

**Comment by andersmmg** [comment]
Ah okay, so it's just my luck lol

**Comment by andersmmg** [comment]
Is there a way for it to say something if it fails, rather than just acting like there are none? It could be clearer

**Comment by zeptofine** [comment]
Well currently there's an info error appearing in the debug menu. if you launch the app with the `-debug` flag, you should be able to get some useful data. That line, "Failed to gather stable releases" should show up. But I may add a popup later

**Comment by Victor-IX** [comment]
Oh no not again... I was wondering why it took me 15 min to download the latest 4.2 build xD

**Comment by L0Lock** [comment]
For me it looks like at least one "stable" release ended up in the daily tab:

![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/16049822/e1f4b017-c073-48ae-b511-4628033e41f4)

Using the "ubuntu" release file on KDE Neon 6.0.2.

**Comment by Victor-IX** [comment]
They published a daily build with the new 4.1 stable version: https://builder.blender.org/download/daily/
That's why you have it here, I tested it and it seems to be the same stable build as the main one!

**Comment by xzenocrimzie** [comment]
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/30086671/60541b8d-7c4b-4229-a08b-da0d4155ead7). I can access  [blender.org/release/ ](https://download.blender.org/release/) just fine through a browser. 
Still having botting issue? 

Blender launcher: 2.0.24

**Comment by Victor-IX** [comment]
Yep, stable builds web requests from the Blender launcher are currently being blocked. I've reached out to someone at the Blender Foundation to have some info on what's happening on their end, but I haven't received a response yet.

**Comment by Darkblader24** [comment]
Yes, a popup letting us know whats the issue would be appreciated! It's very irritating that nothing happens after pressing the button. It just makes me click that button more.

**Comment by johnyc90** [comment]
> ![image](https://private-user-images.githubusercontent.com/30086671/317563077-60541b8d-7c4b-4229-a08b-da0d4155ead7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NTU2ODksIm5iZiI6MTcxMTc1NTM4OSwicGF0aCI6Ii8zMDA4NjY3MS8zMTc1NjMwNzctNjA1NDFiOGQtN2M0Yi00MjI5LWEwOGItZGEwZDQxNTVlYWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI5VDIzMzYyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk5ZDA2MjM1ZmJjNmI4M2Q0NTY0MDBiNmQ4YzZmZDUxZTg0OGUwMzdkNTAxNDhjYzhiZmFjYmZjNzU5ZmRlMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.k2eAhOmjvaNBHBOhn5r0eMMyJ5k8efH0bgl2nJV9AsM). I can access [blender.org/release/ ](https://download.blender.org/release/) just fine through a browser. Still having botting issue?
> 
> Blender launcher: 2.0.24

Looking at this it seems that the launcher is only scraping from download.blender.org. At this point, wouldn't it be more productive to start scraping from the mirrors as well? 
I remember when this happened last time that someone talked about cacheing the adresses for the downloads instead of probing it every time. Was this ever implemented? Feels like this could help the project avoid having its requests blocked this often...

**Comment by 2Pz** [comment]
![Blender](https://github.com/Victor-IX/Blender-Launcher-V2/assets/72107431/912f5b0d-0551-4cb8-bb16-a036b2c0100e)
Hmm! I'm confused. I tried scraping[]( "https://download.blender.org/release/") and it worked fine! But I don't get why the Blender launcher app isn't showing the stable builds.

**Comment by 2Pz** [comment]
![Blender](https://github.com/Victor-IX/Blender-Launcher-V2/assets/72107431/4e394be2-8f57-4423-a7a4-229413f615b9)
Hmm! I'm confused. I tried scraping []("https://download.blender.org/release/") and it worked fine! But I don't get why the Blender launcher app isn't showing the stable builds.

**Comment by tprochazka** [comment]
Because of Blender blocking especially Blender Launcher, since it creates too much load on their servers.
Probably by User-Agent
https://github.com/Victor-IX/Blender-Launcher-V2/issues/79#issuecomment-2014152427

**Comment by Victor-IX** [comment]
> I remember when this happened last time that someone talked about cacheing the adresses for the downloads instead of probing it every time. Was this ever implemented? Feels like this could help the project avoid having its requests blocked this often...

Blender Foundation have created an API for the daily build website and they want to do the same for the https://download.blender.org/release/ website but I don't know when they plan to implement that. An API will dramatically reduce the number of requests per user, which will no longer be an issue. Maybe we can still add a build URL cache but this could lead to other issues if it's not made correctly

**Comment by zeptofine** [comment]
At least on master, the scraper remembers the modified date of the top level folders and skips checking the subdirectories if the parent indicates it has not been modified. so it is a minor request simplification. the reason checking stable is so much slower than automated is that we need to make way more requests to check the subdirectories that actually hold the builds

**Comment by zeptofine** [comment]
just checked. it is not in 2.0.24, but when the next version comes around, there will be much fewer/faster scrapes on stable

**Comment by zeptofine** [comment]
What _is_ interesting is that they are _intentionally_ using OUR user agentz and not just a generic request. that means the attacker is either using our software on a large scale or they are spoofing our agent, which is more likely as it is not hard to do. either way it is targeted to inconvenience this software specifically

**Comment by Victor-IX** [comment]
Do you think it's possible to modify our user agent? I know it will probably not change anything because they can update their spoofing agent to the new one, but it can help differentiate requests for the old version of the blender launcher and the new one.

**Comment by Victor-IX** [comment]
Ok it's simple to do, we can change the header and the server will not block the request anymore


`connection_manager.py`
new
```py
self._headers = {"user-agent": f"Blender-Launcher-v2/{self.version} ({get_platform_full()})"}
```
old
```py 
self._headers = {"user-agent": f"Blender Launcher/{self.version} ({get_platform_full()})"}
```

**Comment by tprochazka** [comment]
Yes. I just tested. It works with different user-agent.
