### ISSUE TITLE
Why Blender 4.1.x is in daily panel but not in stable panel ?

### ISSUE THREAD

**Issue by MattRM2** [Victor-IX/Blender-Launcher-V2#89]
Hi,

Just a little question, I don't understand why Blender 4.1 is only getable in the "Daily panel" instead of the "Stable panel". Normally the Blender 4.1 is a stable released, no ?

Thank you,

Matt

**Comment by zeptofine** [comment]
The stable repo we scrape from is currently blocking our requests due to an attack, see #79

**Comment by MattRM2** [comment]
Oki, thank you for your answers. I hope this will be solved soon with the Blender foundation.
Have a nice day

Matt

**Comment by zeptofine** [comment]
Closed in favour of #79
