### ISSUE TITLE
"Unknown locale: en_DE" error during Blender extraction

### ISSUE THREAD

**Issue by xTobiShotz** [Victor-IX/Blender-Launcher-V2#95]
**Describe the bug**
Blender Launcher will be stuck on "Extracting" during the installation of a Blender build and after restarting mark the Blender install as damaged when on a "non-standard" locale (en_DE in my case).  
The extraction is completed and the install seems to not be broken, as I can launch and use the Blender install just fine using the executable without Blender Launcher.

**To Reproduce**
1. Set Windows locale to `English (Germany)` - `en_DE`
2. Try to install any Blender version via the Blender Launcher
3. "Unknown locale: en_DE" error will pop up after extraction is at 100%
4. Restarting the app will mark the install as damaged

**Expected behavior**
Not crashing and instead falling back to whatever english locale is the default. Or a option to select with locale should be used perhaps?

**Screenshots**  
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/40842191/5cde0d7e-05cf-4c3c-bb69-f996e9829620)
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/40842191/b0b0c9cd-b884-4f1a-82d9-acbac4e96ea4)
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/40842191/7563736d-f87b-4e61-b2b2-8f098a4914e9)

**System (please complete the following information):**
 - Operation system: Windows 11
 - Blender Launcher version: v2.1.24
 - Log file: [Blender Launcher.log](https://github.com/Victor-IX/Blender-Launcher-V2/files/14879866/Blender.Launcher.log)

**Additional context**
Launching Blender and settings the Language to English or anything else does not fix it being marked as damaged.

**Comment by marioklos** [comment]
I have exactly the same bug - Extracting never ends. How to fix that bug?

**Comment by ViTa-Plane** [comment]
v2.1.24 is almost unusable in Windows 10 with that bug.
It loos like  v2.1.24  fails to create the .blinfo file

Temp solution is to close the v2.1.24, lunch v2.0.24 in the same folder as v2.1.24

The old version 'fixes' the issue, by adding the missing .blinfo file to the blender folder

Close v2.0.24 and relaunch v2.1.24. Now all works, but it's very annoying to do that every time the new blender release is downloaded

**Comment by zeptofine** [comment]
Downloaded English (Germany) on my computer and I can reproduce this in 2.1.24, however it has been fixed on bdca9418f37672b0cf9af2363c8cbef26f88c59f and works in main. @Victor-IX Should we make a prerelease for people to test it?

**Comment by Victor-IX** [comment]
Yes, we can do that!

**Comment by Victor-IX** [comment]
@ViTa-Plane 
The fix is available in a pre-release build. If you want, you can turn on pre-release in the settings and update your launcher to have the fix.

**Comment by xTobiShotz** [comment]
Working for me as of v2.2.0-rc, Thank you!
I'll leave this open since you've asked someone else to test, feel free to close whenever.
