### ISSUE TITLE
Cant open settings in blender launcher 2.1.24

### ISSUE THREAD

**Issue by lolpowerluke** [Victor-IX/Blender-Launcher-V2#96]
**Describe the bug**
Settings dont open in version 2.1.24

**To Reproduce**
1. Open blender launcher 2.1.24
2. Click on the settings icon at the top

**Expected behavior**
Settings open in new window

**Screenshots**
settings icon: ![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/47672899/cf10d3ab-a147-46aa-93cd-fac9f8d74cce)

**System (please complete the following information):**
 - Operation system: Windows 11
 - Blender Launcher version: 2.1.24
 - Log file: Where can I find this?

**Additional context**
Dont know if important, but I just updated from 2.0.24

**Comment by zeptofine** [comment]
That usually means the window failed to read your settings. the log file should be in %LOCALAPPDATA%/Blender Launcher on windows

**Comment by lolpowerluke** [comment]
ty, here it is
[Blender Launcher.log](https://github.com/Victor-IX/Blender-Launcher-V2/files/14890626/Blender.Launcher.log)

**Comment by zeptofine** [comment]
hmm, could you try to reset your minimum scraped version manually in the file? it doesnt seem to like the minor version, whatever was there. maybe you had a strange floating point number in it

**Comment by zeptofine** [comment]
I can confirm this by making a messed up minimum_blender_stable_version 
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/54873330/6c83e561-a2d9-401b-b641-93ea73a32eb2)

**Comment by lolpowerluke** [comment]
![image](https://github.com/Victor-IX/Blender-Launcher-V2/assets/47672899/85b8cd81-8730-402f-8814-9a032aa46da5)
it had this in it, so that was probably it, setting it to 3.0 fixed it

**Comment by zeptofine** [comment]
nice. not sure how this couldve happened, even with floating point imprecision
